name: build-and-push-container-image
on:
  workflow_dispatch:
    inputs:
      environment:
        description: specify the image repository environment.
        required: true
        default: dev
      build_target:
        description: Tag name of branch name to deploy e.g. main, develop, v1.0.0 etc.
        required: true
        default: main
permissions:
  id-token: write
  contents: read
jobs:
  build-and-push-container-image:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.build_target }}
      - name: Get image tag
        id: get-image-tag
        run: |
          SHORT_COMMIT_ID=`git rev-parse --short HEAD`
          REF=`echo ${{ github.event.inputs.build_target }} | sed  -e 's/\//-/g'`
          echo "image-tag=${REF}-${SHORT_COMMIT_ID}" >> $GITHUB_OUTPUT
      - name: Assume role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN_TO_PUSH_IMAGE }}
          aws-region: ap-northeast-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push image to Amazon ECR
        uses: docker/build-push-action@v3
        with:
          context: "image"
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/sample-${{ github.event.inputs.environment}}-web:${{ steps.get-image-tag.outputs.image-tag }}
